#nullable enable

// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =====================================================================

using System.Net;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GrpcWebBridge.Domain.Exceptions;

/// <summary>
/// Represents a Problem Details object as defined in RFC 7807.
/// Provides a machine-readable format for specifying errors in HTTP API responses.
/// </summary>
/// <remarks>
/// The Problem Details format is standardized by RFC 7807 and provides:
/// - type: A URI reference that identifies the problem type
/// - title: A short, human-readable summary of the problem type
/// - status: The HTTP status code generated by the origin server
/// - detail: A human-readable explanation specific to this occurrence
/// - instance: A URI reference that identifies the specific occurrence
/// </remarks>
public sealed class ProblemDetails
{
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type.
    /// When dereferenced, it should provide human-readable documentation for the problem type.
    /// </summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code ([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("status")]
    public int? Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// It may or may not yield further information if dereferenced.
    /// </summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; set; }

    /// <summary>
    /// An object containing additional, problem-specific details.
    /// </summary>
    [JsonExtensionData]
    public Dictionary<string, object?> Extensions { get; set; } = new(StringComparer.Ordinal);

    /// <summary>
    /// Gets or sets the trace identifier for correlation with distributed tracing systems.
    /// </summary>
    [JsonIgnore]
    public string? TraceId { get; set; }

    /// <summary>
    /// Gets or sets the request path where the error occurred.
    /// </summary>
    [JsonIgnore]
    public string? Path { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when the error occurred.
    /// </summary>
    [JsonIgnore]
    public DateTime? Timestamp { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProblemDetails"/> class.
    /// </summary>
    public ProblemDetails()
    {
        Type = "about:blank";
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProblemDetails"/> class with the specified type.
    /// </summary>
    /// <param name="type">The problem type URI.</param>
    public ProblemDetails(string type)
    {
        Type = type;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="ProblemDetails"/> class with the specified type and status.
    /// </summary>
    /// <param name="type">The problem type URI.</param>
    /// <param name="status">The HTTP status code.</param>
    public ProblemDetails(string type, int status)
    {
        Type = type;
        Status = status;
    }

    /// <summary>
    /// Returns a string representation of the ProblemDetails.
    /// </summary>
    public override string ToString()
    {
        return $"ProblemDetails(Type={Type}, Status={Status}, Title={Title}, Detail={Detail})";
    }

}
